[project]
name = "2026-fx-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dash>=2.16.0",
    "dash-bootstrap-components>=1.5.0",
    "numpy>=1.26.0",
    "pandas>=2.1.0",
    "plotly>=5.18.0",
    "requests>=2.34.2",
    "yfinance>=0.2.40",
]
