# Generated by Django 2.1 on 2021-01-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='投稿者名')),
                ('password', models.CharField(max_length=255, verbose_name='投稿者パスワード')),
                ('content', models.TextField(max_length=1000, verbose_name='投稿内容')),
                ('votes', models.IntegerField(default=0, verbose_name='投票数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='コメント者名')),
                ('password', models.CharField(max_length=255, verbose_name='コメント者パスワード')),
                ('content', models.TextField(max_length=1000, verbose_name='コメント内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='コメント記入日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Article')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
